### ISSUE TITLE
ScanPC is not giving any output

### ISSUE THREAD

**Issue by BhagyashreeKoyande** [alevoski/ScanPC#2]
Thankyou

**Comment by alevoski** [comment]
Hi,

I think of two things with the screenshot you posted and the problem you described :

- Firstly, it shows you are using Mingw64 to run the code, I never test my code with it : maybe its the cause (I will test asap to be sure).

- Secondly, I have already, randomly and quite rarely, encounter the stopping cursor when the script prompt for user input (y or n).

If you reproduce this issue, **could you press any other keys (like "enter") and see if the script continue** ?
